### ISSUE TITLE
Duplicate IDs and Lock errors

### ISSUE THREAD

**Issue by b-gehrke** [ontology-tools/onto-spread-ed#30]
Sometimes when during the saving process duplicate ids are generated as reported here https://github.com/HumanBehaviourChangeProject/ontologies/issues/543.

In the logs lock errors occur.

```
	Traceback (most recent call last):
	  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
	    self.run()
	  File "/usr/lib/python3.8/threading.py", line 870, in run
	    self._target(*self._args, **self._kwargs)
	  File "/var/www/html/onto-spread-ed/./SpreadsheetSearcher.py", line 67, in update_index
	    writer = ix.writer()
	  File "/var/www/html/onto-spread-ed/venv/lib/python3.8/site-packages/whoosh/index.py", line 464, in writer
	    return SegmentWriter(self, **kwargs)
	  File "/var/www/html/onto-spread-ed/venv/lib/python3.8/site-packages/whoosh/writing.py", line 515, in __init__
	    raise LockError
	whoosh.index.LockError
```

**Comment by b-gehrke** [comment]
The lock error comes from the the index writer. It tries to lock a file (probably to sync across processes) and fails if this does not succeed immediately. This could e.g. occur if the index is updated (asynchronously) after two consecutive saves.

**Comment by b-gehrke** [comment]
The writer uses an internal lock to ensure only one writer exists at the time. But it does not wait for the lock and fails immediately if the lock cannot be acquired. I added a timeout of 60s and ensured that the thread lock is released even if there is an error.

@jannahastings can you redeploy the app? I hope it fixes the error or at least reduces its chance to occur.

**Comment by jannahastings** [comment]
Deployed!
